# Generated by Django 5.2.1 on 2025-05-31 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Packing',
            fields=[
                ('part_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('stock_qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('part_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
            ],
        ),
    ]
