# Generated by Django 5.2.1 on 2025-06-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='packingdetail',
            unique_together=set(),
        ),
    ]
