# Generated by Django 5.2.1 on 2025-05-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('total_qty', models.IntegerField()),
                ('box_mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty_per_box', models.IntegerField()),
                ('case_no_start', models.IntegerField()),
                ('case_no_end', models.IntegerField()),
                ('total_box', models.IntegerField()),
                ('net_wt', models.FloatField()),
                ('gross_wt', models.FloatField()),
                ('length', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('cbm', models.FloatField()),
            ],
        ),
    ]
