# Generated by Django 5.2.1 on 2025-06-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='packingdetail',
            old_name='box_mrp',
            new_name='mrp_box',
        ),
        migrations.RenameField(
            model_name='packingdetail',
            old_name='update_box_mrp',
            new_name='mrp_invoice',
        ),
        migrations.AddField(
            model_name='stock',
            name='brand_name',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packingdetail',
            name='gross_wt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='packingdetail',
            name='gst',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packingdetail',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packingdetail',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='packingdetail',
            name='net_wt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='packingdetail',
            name='total_gross_wt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='packingdetail',
            name='total_net_wt',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='packingdetail',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
