# Generated by Django 5.2.1 on 2025-08-23 11:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_ruppes_client_rupees'),
        ('packing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='client.client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='part_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together={('client', 'part_no')},
        ),
    ]
