# Generated by Django 5.2.1 on 2025-06-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_rename_box_mrp_packingdetail_mrp_box_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingdetail',
            name='brand_name',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
