# Generated by Django 5.2.1 on 2025-06-14 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0002_alter_packingdetail_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetWeight',
            fields=[
                ('part_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('net_wt', models.DecimalField(decimal_places=3, max_digits=10)),
            ],
        ),
    ]
