# Generated by Django 5.2.1 on 2025-06-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing', '0003_packingdetail_brand_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packingdetail',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
