# Generated by Django 5.2.1 on 2025-08-12 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
