# Generated by Django 5.2.1 on 2025-08-12 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_last_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
