# Generated by Django 5.2.1 on 2025-08-12 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_last_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_refresh_jti',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
