# Generated by Django 5.2.1 on 2025-08-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_customuser_last_refresh_jti'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='parent_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
