# Generated by Django 5.2.1 on 2025-09-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='permission',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
