# Generated by Django 5.2.1 on 2025-07-23 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('marka', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('vessel_no', models.CharField(max_length=100)),
                ('port_of_loding', models.CharField(max_length=100)),
                ('terms_of_payment', models.TextField()),
                ('dilivery_terms', models.TextField()),
                ('port_of_discharge', models.CharField(max_length=100)),
                ('final_destination', models.CharField(max_length=100)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'client_name', 'marka'), name='unique_client_per_user')],
            },
        ),
    ]
