# Generated by Django 5.2.1 on 2025-07-23 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='port_of_loding',
            new_name='port_of_loading',
        ),
    ]
