# Generated by Django 5.2.1 on 2025-07-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_rename_port_of_loding_client_port_of_loading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='dilivery_terms',
            new_name='delivery_terms',
        ),
    ]
