# Generated by Django 5.2.1 on 2025-07-25 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_rename_dilivery_terms_client_delivery_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='gst',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='ruppes',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
