# Generated by Django 5.2.1 on 2025-07-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_client_gst_client_ruppes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='ruppes',
            new_name='rupees',
        ),
    ]
