# Generated by Django 5.2.1 on 2025-07-01 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MergedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amt_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_percent', models.CharField(blank=True, max_length=10, null=True)),
                ('hsn', models.CharField(blank=True, max_length=100, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merged_items', to='client.client')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('part_no', 'client'), name='unique_mergeditem_per_client')],
            },
        ),
    ]
