# Generated by Django 5.2.1 on 2025-07-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asstimate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeditem',
            name='effective_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
