# Generated by Django 5.2.1 on 2025-07-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asstimate', '0002_mergeditem_effective_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mergeditem',
            name='tax_percent',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
