# Generated by Django 5.2.1 on 2025-07-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asstimate', '0003_alter_mergeditem_tax_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='mergeditem',
            name='doller_effective_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
