# Generated by Django 5.2.1 on 2025-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('part_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amt_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('billed_qty', models.IntegerField(blank=True, null=True)),
                ('total_amt_billed_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
        ),
    ]
