# Generated by Django 5.2.1 on 2025-06-11 09:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('qty', models.IntegerField()),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amt_mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('billed_qty', models.IntegerField(blank=True, null=True)),
                ('total_amt_billed_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('client_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client_name', 'part_no'), name='unique_client_part')],
            },
        ),
    ]
