# Generated by Django 5.2.1 on 2025-06-11 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
        ('orderItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_client_part',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='client_name',
            new_name='client',
        ),
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('client', 'part_no'), name='unique_client_part'),
        ),
    ]
