# Generated by Django 5.2.1 on 2025-08-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderItem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='item',
            name='unique_client_part',
        ),
    ]
