# Generated by Django 5.2.1 on 2025-08-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_rename_ruppes_client_rupees'),
        ('orderItem', '0002_remove_item_unique_client_part'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(fields=('client', 'part_no'), name='unique_client_part'),
        ),
    ]
