# Generated by Django 5.2.1 on 2025-07-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('item_code', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('item_description', models.TextField()),
                ('mrp_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn_code', models.IntegerField()),
                ('gst_percent', models.CharField()),
            ],
        ),
    ]
