# Generated by Django 5.2.1 on 2025-09-07 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('mrp_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hsn_code', models.IntegerField()),
                ('gst_percent', models.IntegerField()),
                ('brand_name', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'part_no')},
            },
        ),
    ]
