# Generated by Django 5.2.1 on 2025-07-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='gst_percent',
            field=models.IntegerField(),
        ),
    ]
