# Generated by Django 5.2.1 on 2025-08-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exceldata',
            old_name='item_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='exceldata',
            old_name='item_code',
            new_name='part_no',
        ),
    ]
