# Generated by Django 5.2.1 on 2025-07-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='gst_percent',
            field=models.CharField(max_length=10),
        ),
    ]
