# Generated by Django 5.2.1 on 2025-09-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='permission',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
