# Generated by Django 5.2.1 on 2025-06-10 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='hsn_code',
            field=models.IntegerField(),
        ),
    ]
