# Generated by Django 5.2.1 on 2025-08-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0002_rename_item_description_exceldata_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exceldata',
            name='brand_name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
