# Generated by Django 5.2.1 on 2025-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0002_alter_exceldata_hsn_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exceldata',
            name='gst_percent',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
