# Generated by Django 5.2.1 on 2025-09-07 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('excelFile', '0002_exceldata_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exceldata',
            name='permission',
        ),
    ]
