# Generated by Django 5.2.1 on 2025-07-23 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('qty', models.IntegerField()),
                ('per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('client', 'part_no'), name='unique_client_part_invoice')],
            },
        ),
    ]
